title: Activist Collective
subheads:
    - "This site is built with the collective in mind."
    - "We fight as one because we are one."

email: false
description: "This site is built with the collective in mind. We fight as one because we are one."
baseurl: ""
url: "https://activistcollective.org/"

header_image: "/images/cover.webp"

# uncomment and fill in any social IDs you want linked from the top of your page

# email: "email@example.com"
# tiktok_username: "my_tiktok_username"
# github_username: "my_github_username"
instagram_username: "mommawearsdadjeans"
# threads_username: "my_threads_username"
# pinterest_username: "my_pinterest_username"
# mastodon_username: "@username@example.host"
# cashapp_username: "my_cashapp_username"
# venmo_username: "my_venmo_username"
bluesky_username: "jesstok.bsky.social"
# telephone_number: "999-999-9999"
discord_username: "HuRCMc5f"
youtube_username: "momma_wears_dad_jeans1"

# uncomment for plausible.io analytics, should match the "url" above
# plausible_io: example.com

# uncomment to add your google analytics
# google_analytics: UA-NNNNNNNN-N

# Build settings
theme: jekyll-theme-linky
plugins:
    - jekyll-feed

exclude:
    - VERSION
    - bin
    - linky.gemspec
    - netlify.toml
    - scripts

linky:
    body_background: "#929292"
    body_foreground: "#000"
    button_background: "#44e660"
    button_foreground: "#000"
    social_button_color: "#44e660"

collections:
    - links

# tell the jekyll-feed plugin to include the links collection
feed:
    collections:
        - links
